sudo: false
language: "node_js"
node_js:
  - "4.2"
  - "5.0"
script:
  - npm install istanbul
  - istanbul cover ./node_modules/.bin/_mocha --report lcovonly
after_script:
  - npm install coveralls
  - COVERALLS_ENDPOINT="http://knappi.org:8040" cat ./coverage/lcov.info | coveralls 